### ISSUE TITLE
Make the Copy option more functional.

### ISSUE THREAD

**Issue by Chayandev** [jatiinyadav/Color-Palettes#3]
Hey @jatiinyadav I have seen that copy is working well but, for better user experience and make it more optimal when copy is done one little change should be there either copy should be changed to copied, else one toast SMS will be shown ad copied.

If you feel this is helpful to your website, please assign me this issue to work with it.

**Comment by jatiinyadav** [comment]
@Chayandev You can work on this issue.

**Comment by Chayandev** [comment]
Ok .

**Comment by jatiinyadav** [comment]
This issue is being resolved in [PR](https://github.com/jatiinyadav/Color-Palettes/pull/4)
